
Showing logs for build [32mqbitflames-python-app-1-master-lfv66-1[0m stage [32mfrom-build-pack[0m and container [32mcredential-initializer[0m
{"level":"info","ts":1609681569.6961262,"caller":"creds-init/main.go:44","msg":"Credentials initialized."}

Showing logs for build [32mqbitflames-python-app-1-master-lfv66-1[0m stage [32mfrom-build-pack[0m and container [32mworking-dir-initializer[0m

Showing logs for build [32mqbitflames-python-app-1-master-lfv66-1[0m stage [32mfrom-build-pack[0m and container [32mplace-tools[0m

Showing logs for build [32mqbitflames-python-app-1-master-lfv66-1[0m stage [32mfrom-build-pack[0m and container [32mstep-git-source-qbitflames-python-app-1-master-lfv66-zwgcj[0m
{"level":"info","ts":1609681589.7672718,"caller":"git/git.go:105","msg":"Successfully cloned https://github.com/qbitflames/python-app-1.git @ v0.0.1 in path /workspace/source"}
{"level":"warn","ts":1609681589.767368,"caller":"git/git.go:152","msg":"Unexpected error: creating symlink: symlink /tekton/home/.ssh /root/.ssh: file exists"}
{"level":"info","ts":1609681589.8051808,"caller":"git/git.go:133","msg":"Successfully initialized and updated submodules in path /workspace/source"}

Showing logs for build [32mqbitflames-python-app-1-master-lfv66-1[0m stage [32mfrom-build-pack[0m and container [32mstep-setup-builder-home[0m

Showing logs for build [32mqbitflames-python-app-1-master-lfv66-1[0m stage [32mfrom-build-pack[0m and container [32mstep-git-merge[0m
Using SHAs from PULL_REFS=master:
WARNING: no SHAs to merge, falling back to initial cloned commit

Showing logs for build [32mqbitflames-python-app-1-master-lfv66-1[0m stage [32mfrom-build-pack[0m and container [32mstep-setup-jx-git-credentials[0m
Generated Git credentials file /workspace/xdg_config/git/credentials

Showing logs for build [32mqbitflames-python-app-1-master-lfv66-1[0m stage [32mfrom-build-pack[0m and container [32mstep-build-python-unittest[0m

----------------------------------------------------------------------
Ran 0 tests in 0.000s

OK

Showing logs for build [32mqbitflames-python-app-1-master-lfv66-1[0m stage [32mfrom-build-pack[0m and container [32mstep-build-container-build[0m
E0103 13:46:33.610663       9 aws_credentials.go:77] while getting AWS credentials NoCredentialProviders: no valid providers in chain. Deprecated.
	For verbose messaging see aws.Config.CredentialsChainVerboseErrors
[36mINFO[0m[0001] Using dockerignore file: /workspace/source/.dockerignore 
[36mINFO[0m[0001] Retrieving image manifest python:onbuild     
E0103 13:46:34.447313       9 metadata.go:154] while reading 'google-dockercfg' metadata: http status code: 404 while fetching url http://metadata.google.internal./computeMetadata/v1/instance/attributes/google-dockercfg
E0103 13:46:34.449624       9 metadata.go:166] while reading 'google-dockercfg-url' metadata: http status code: 404 while fetching url http://metadata.google.internal./computeMetadata/v1/instance/attributes/google-dockercfg-url
[36mINFO[0m[0002] Retrieving image manifest python:onbuild     
[36mINFO[0m[0003] Built cross stage deps: map[]                
[36mINFO[0m[0003] Retrieving image manifest python:onbuild     
[36mINFO[0m[0003] Retrieving image manifest python:onbuild     
[36mINFO[0m[0004] Executing 3 build triggers                   
[36mINFO[0m[0004] Checking for cached layer gcr.io/weighty-nation-272311/cache:4603157fb951c8b4502529c64ddc571c85e381ce4686ea05728e14a56a118e66... 
[36mINFO[0m[0004] No cached layer found for cmd COPY requirements.txt /usr/src/app/ 
[36mINFO[0m[0004] cmd: EXPOSE                                  
[36mINFO[0m[0004] Adding exposed port: 8080/tcp                
[36mINFO[0m[0004] Unpacking rootfs as cmd COPY requirements.txt /usr/src/app/ requires it. 
[36mINFO[0m[0020] COPY requirements.txt /usr/src/app/          
[36mINFO[0m[0020] Resolving 1 paths                            
[36mINFO[0m[0020] Taking snapshot of files...                  
[36mINFO[0m[0021] RUN pip install --no-cache-dir -r requirements.txt 
[36mINFO[0m[0021] Taking snapshot of full filesystem...        
[36mINFO[0m[0021] Pushing layer gcr.io/weighty-nation-272311/cache:4603157fb951c8b4502529c64ddc571c85e381ce4686ea05728e14a56a118e66 to cache now 
[36mINFO[0m[0023] Resolving 27638 paths                        
[36mINFO[0m[0027] cmd: /bin/sh                                 
[36mINFO[0m[0027] args: [-c pip install --no-cache-dir -r requirements.txt] 
[36mINFO[0m[0027] Running: [/bin/sh -c pip install --no-cache-dir -r requirements.txt] 
You are using pip version 10.0.1, however version 20.3.3 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
[36mINFO[0m[0029] Taking snapshot of full filesystem...        
[36mINFO[0m[0029] Resolving 28054 paths                        
[36mINFO[0m[0032] Pushing layer gcr.io/weighty-nation-272311/cache:26208b704f381cfc1f456d1b1b9697de2e61930f2b836f1a4480488b7e191354 to cache now 
[36mINFO[0m[0032] COPY . /usr/src/app                          
[36mINFO[0m[0032] Resolving 115 paths                          
[36mINFO[0m[0032] Taking snapshot of files...                  
[36mINFO[0m[0032] Pushing layer gcr.io/weighty-nation-272311/cache:80c19d9934ddd6f301d0935d77fa144392353a8318cde2a5d05141cb7f0cd7d0 to cache now 
[36mINFO[0m[0032] COPY requirements.txt .                      
[36mINFO[0m[0032] Resolving 1 paths                            
[36mINFO[0m[0032] Taking snapshot of files...                  
[36mINFO[0m[0032] ENV PORT 8080                                
[36mINFO[0m[0032] No files changed in this command, skipping snapshotting. 
[36mINFO[0m[0032] EXPOSE 8080                                  
[36mINFO[0m[0032] cmd: EXPOSE                                  
[36mINFO[0m[0032] Adding exposed port: 8080/tcp                
[36mINFO[0m[0032] No files changed in this command, skipping snapshotting. 
[36mINFO[0m[0032] ENTRYPOINT ["python"]                        
[36mINFO[0m[0032] No files changed in this command, skipping snapshotting. 
[36mINFO[0m[0032] CMD ["app.py"]                               
[36mINFO[0m[0032] No files changed in this command, skipping snapshotting. 
[36mINFO[0m[0032] Pushing layer gcr.io/weighty-nation-272311/cache:573a45fb0635afab74dd54e3f6d59686d97f96e45c09866a44621193814029d6 to cache now 

Showing logs for build [32mqbitflames-python-app-1-master-lfv66-1[0m stage [32mfrom-build-pack[0m and container [32mstep-build-post-build[0m
no CVE provider running in the current ** namespace so skip adding image to be analysed

Showing logs for build [32mqbitflames-python-app-1-master-lfv66-1[0m stage [32mfrom-build-pack[0m and container [32mstep-promote-changelog[0m
Converted /workspace/source/charts/python-app-1 to an unshallow repository
Generating change log from git ref e85f1b18eaf582ec1bb7d1b648ae6630446b1088 => 8e7cb19f3dbe219b11968513414bf8de71c26e34
Associating user qasim-aziz in users.jenkins.io with email envoyfacilitation@outlook.com to git GitProvider user with login qasim-aziz-0 as emails match
Adding label jenkins.io/git-github-userid=qasim-aziz-0 to user qasim-aziz in users.jenkins.io
Finding issues in commit messages using git format
WARNING: No release found for qbitflames/python-app-1 and tag v0.0.1 so creating a new release
Updated the release information at https://github.com/qbitflames/python-app-1/releases/tag/v0.0.1
generated: /workspace/source/charts/python-app-1/templates/release.yaml
Created Release python-app-1-0-0-1 resource in namespace **
Updating PipelineActivity qbitflames-python-app-1-master-1 with version 0.0.1
Updated PipelineActivities qbitflames-python-app-1-master-1 with release notes URL: https://github.com/qbitflames/python-app-1/releases/tag/v0.0.1

Showing logs for build [32mqbitflames-python-app-1-master-lfv66-1[0m stage [32mfrom-build-pack[0m and container [32mstep-promote-helm-release[0m
WARNING: No $CHART_REPOSITORY defined so using the default value of: http://jenkins-x-chartmuseum:8080
Adding missing Helm repo: storage.googleapis.com https://storage.googleapis.com/chartmuseum.jenkins-x.io
Successfully added Helm repository storage.googleapis.com.
Adding missing Helm repo: jenkins-x-chartmuseum http://jenkins-x-chartmuseum:8080
Successfully added Helm repository jenkins-x-chartmuseum.
WARNING: No $CHART_REPOSITORY defined so using the default value of: http://jenkins-x-chartmuseum:8080
Uploading chart file python-app-1-0.0.1.tgz to http://jenkins-x-chartmuseum:8080/api/charts
Received 401 response: {"error":"unauthorized"}
error: Failed to post chart to http://jenkins-x-chartmuseum:8080/api/charts due to response 401: {"error":"unauthorized"}
[31m
Pipeline failed on stage 'from-build-pack' : container 'step-promote-helm-release'. The execution of the pipeline has stopped.[0m
